name: VFXNaming CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04
    environment:
      name: coverage
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7","3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Lint with Ruff
      if: matrix.python-version == '3.11'
      run: |
        tox -e ruffci
      continue-on-error: true
    - name: Run tests with Python 3.7
      if: matrix.python-version == '3.7'
      run: |
        tox -e py37ci
    - name: Run tests with Python 3.10
      if: matrix.python-version == '3.10'
      run: |
        tox -e py310ci
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      
