name: VFXNaming CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pipenv'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv tox
        pipenv sync
        pipenv shell
    - name: Lint with Ruff
      run: |
        ruff check --output-format=github .
      continue-on-error: true
    - name: Run tests with tox
      run: |
        tox -e py310ci
    - name: Test with pytest
      run: |
        pytest
